# User Management Service Configuration
# Java 25 + Spring Boot 4 with Virtual Threads

server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    # Enable virtual threads
    virtual-threads: true

spring:
  # Virtual threads configuration
  threads:
    virtual:
      enabled: true
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Validation configuration
  validation:
    enabled: true

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,observations
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      application: user-management-service
      version: "1.0.0"
      java-version: "25"

# Logging configuration
logging:
  level:
    com.example.usermanagement: DEBUG
    org.springframework.observation: DEBUG
    org.springframework.web.client: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

# Application specific configuration
app:
  viacep:
    base-url: https://viacep.com.br/ws
    timeout: 5000
  validation:
    cpf-regex: "^\\d{11}$"
    email-regex: "^[A-Za-z0-9+_.-]+@(.+)$"
    postal-code-regex: "^\\d{8}$"
